import { Gender } from "../src/models/users/Gender";
import { IProfessionalUser } from "../src/models/users/ProfessionalUser.interface";

// Users array for test.
export const users: IProfessionalUser[] = [
    {
        email: "test@gmail.com",
        name: "Juan",
        last_name: "Gomez",
        dni: "34612333",
        province: "Santa Fe",
        city: "Rosario",
        tel: "549341233311",
        link: "web_site.com.ar",
        about_me:
            "¡Hola! Soy un plomero con más de 15 años de experiencia en reparaciones y mantenimiento de sistemas de fontanería. Mi objetivo es brindar soluciones efectivas y duraderas para que tus sistemas de agua funcionen sin problemas. He trabajado en una variedad de proyectos, desde hogares hasta edificios comerciales. Si buscas a un profesional confiable para solucionar tus problemas de fontanería, estaré encantado de ayudarte.",
        gender: Gender.male,
        birth_date: "1990-01-30",
        auth_number: "2333122333",
        img: "image.png",
        category_id: "2",
    },
    {
        email: "another_user@gmail.com",
        name: "Maria",
        last_name: "Lopez",
        dni: "56789012",
        province: "Buenos Aires",
        city: "La Plata",
        tel: "549341456789",
        link: "another_site.com.ar",
        about_me:
            "¡Hola a todos! Soy una carpintera apasionada por el diseño y la creación de muebles únicos y funcionales. Mi experiencia abarca desde pequeñas piezas de mobiliario hasta proyectos de carpintería a gran escala. Mi objetivo es combinar la estética con la funcionalidad para ofrecer resultados que se adapten a tus necesidades. Si buscas añadir calidez y originalidad a tus espacios, estaré encantada de colaborar en tus proyectos.",
        gender: Gender.female,
        birth_date: "1985-05-15",
        auth_number: "9876543210",
        img: "another_image.png",
        category_id: "2",
    },
    {
        email: "test3@gmail.com",
        name: "Carlos",
        last_name: "Martinez",
        dni: "11223344",
        province: "Cordoba",
        city: "Cordoba",
        tel: "549341987654",
        link: "web_site_3.com.ar",
        about_me:
            "¡Hola a todos! Soy un electricista matriculado con experiencia en instalaciones eléctricas residenciales y comerciales. Mi objetivo es garantizar la seguridad y eficiencia de tus sistemas eléctricos. He trabajado en proyectos de diversa magnitud, desde pequeñas reparaciones hasta nuevas instalaciones. Si buscas un profesional dedicado a brindar soluciones eléctricas confiables, estaré encantado de ser tu elección.",
        gender: Gender.male,
        birth_date: "1988-08-20",
        auth_number: "555566667777",
        img: "image3.png",
        category_id: "1",
    },
    {
        email: "test4@gmail.com",
        name: "Laura",
        last_name: "Fernandez",
        dni: "99887766",
        province: "Mendoza",
        city: "Mendoza",
        tel: "549341112233",
        link: "web_site_4.com.ar",
        about_me:
            " ¡Hola a todos! Soy una albañila con experiencia en construcción y renovación de estructuras. Mi objetivo es crear espacios seguros y funcionales a través de soluciones de construcción eficientes. He trabajado en una variedad de proyectos, desde viviendas hasta edificios comerciales. Si buscas una profesional comprometida con la calidad y la durabilidad, estaré encantada de colaborar en tus proyectos.",
        gender: Gender.female,
        birth_date: "1982-12-10",
        auth_number: "333344445555",
        img: "image4.png",
        category_id: "5",
    },
    {
        email: "test5@gmail.com",
        name: "Raul",
        last_name: "Perez",
        dni: "55443322",
        province: "San Juan",
        city: "San Juan",
        tel: "549341445566",
        link: "web_site_5.com.ar",
        about_me:
            "Saludos, soy un carpintero con pasión por el diseño y la creación de piezas de madera únicas y funcionales. Mi experiencia abarca desde pequeñas piezas de mobiliario hasta proyectos de carpintería a gran escala. Mi objetivo es fusionar la estética con la funcionalidad para crear piezas que se adapten a tus necesidades. Si buscas añadir calidez y originalidad a tus espacios, estaré encantado de colaborar en tus proyectos.",
        gender: Gender.male,
        birth_date: "1975-03-05",
        auth_number: "999900001111",
        img: "image5.png",
        category_id: "3",
    },
    {
        email: "test6@gmail.com",
        name: "Alex",
        last_name: "Taylor",
        dni: "98765432",
        province: "Neuquen",
        city: "Neuquen",
        tel: "549341223344",
        link: "web_site_6.com.ar",
        about_me:
            "¡Hola! Soy un albañil no binarie con experiencia en construcción y reparación estructural. Mi objetivo es construir bases sólidas para edificaciones duraderas. He trabajado en una variedad de proyectos, desde pequeñas reparaciones hasta construcciones de mayor envergadura. Mi pasión por la construcción y mi atención a los detalles me permiten entregar resultados sólidos y confiables. Si buscas un/a albañil comprometidx con la calidad, estoy aquí para ayudarte.",
        gender: Gender.nonBinary,
        birth_date: "1993-07-12",
        auth_number: "777788889999",
        img: "image6.png",
        category_id: "5",
    },
    {
        email: "test7@gmail.com",
        name: "Jordan",
        last_name: "Smith",
        dni: "33445566",
        province: "Salta",
        city: "Salta",
        tel: "549341556677",
        link: "web_site_7.com.ar",
        about_me:
            " ¡Hola! Como fontanerx no binarie, me dedico a resolver problemas de cañerías y sistemas de agua con eficiencia y precisión. Mi experiencia abarca desde reparaciones rápidas hasta instalaciones completas. Mi enfoque es brindar soluciones confiables y duraderas para asegurar que el agua fluya sin problemas. Si buscas a alguien que se preocupe por mantener tus sistemas de agua en óptimas condiciones, estaré encantadx de ayudarte.",
        gender: Gender.nonBinary,
        birth_date: "1980-09-25",
        auth_number: "1234567890",
        img: "image7.png",
        category_id: "2",
    },
];
