basePath: null
definitions:
    IAuthProfessionalUser:
        description: ""
        properties:
            email:
                type: string
                description: ""
            password:
                type: string
                description: ""
            name:
                type: string
                description: ""
            lastname:
                type: string
                description: ""
            dni:
                type: string
                description: ""
            province:
                type: string
                description: ""
            city:
                type: string
                description: ""
            tel:
                type: string
                description: ""
            link:
                type: string
                description: ""
            about_me:
                type: string
                description: ""
            gender:
                type: string
                description: ""
            birthdate:
                type: string
                description: ""
            auth_number:
                type: string
                description: ""
            img:
                type: string
                description: ""
            created_at:
                type: string
                description: ""
            category_id:
                type: string
                description: ""
        type: object
        required:
            - email
            - password
            - name
            - lastname
            - dni
            - province
            - city
            - tel
            - gender
            - birthdate
            - created_at
            - category_id
    ICategory:
        description: ""
        properties:
            id:
                type: number
                format: double
                description: ""
            name:
                type: string
                description: ""
        type: object
        required:
            - id
            - name
    IProfessionalUser:
        description: ""
        properties:
            id:
                type: number
                format: double
                description: ""
            email:
                type: string
                description: ""
            name:
                type: string
                description: ""
            lastname:
                type: string
                description: ""
            dni:
                type: string
                description: ""
            province:
                type: string
                description: ""
            city:
                type: string
                description: ""
            tel:
                type: string
                description: ""
            link:
                type: string
                description: ""
            about_me:
                type: string
                description: ""
            gender:
                type: string
                description: ""
            birthdate:
                type: string
                description: ""
            auth_number:
                type: string
                description: ""
            img:
                type: string
                description: ""
            category_id:
                type: string
                description: ""
        type: object
        required:
            - email
            - name
            - lastname
            - dni
            - province
            - city
            - tel
            - gender
            - birthdate
            - category_id
info:
    description: 'FastWork API.'
    license:
        name: ISC
    title: fastwork-api
    version: 1.0.0
paths:
    /api/auth/signup:
        post:
            operationId: AuthPost
            produces:
                - text/html
            responses:
                '200':
                    description: Ok
                    schema:
                        type: string
                '201':
                    description: 'Professional User created'
                    schema:
                        type: string
                '400':
                    description: 'Bad request'
                    schema:
                        type: string
                '500':
                    description: 'Error server'
                    schema:
                        type: string
            description: ""
            tags:
                - AuthUser
            consumes:
                - application/json
            parameters:
                -
                    description: ""
                    in: body
                    name: authUser
                    required: true
                    schema:
                        $ref: '#/definitions/IAuthProfessionalUser'
    /api/categories/:
        get:
            operationId: CategoriesGet
            produces:
                - application/json
                - text/html
            responses:
                '200':
                    description: Success
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/ICategory'
                '500':
                    description: 'No connection to database'
                    schema:
                        type: string
            description: ""
            tags:
                - Categories
            parameters: []
        post:
            operationId: CategoriesPost
            produces:
                - text/html
            responses:
                '201':
                    description: 'Created category'
                    schema:
                        type: string
                '204':
                    description: 'No content'
                '500':
                    description: 'Server error'
                    schema:
                        type: string
            description: ""
            tags:
                - Admin
            security:
                -
                    default:
                        - x-auth
            consumes:
                - application/json
            parameters:
                -
                    description: ""
                    in: body
                    name: category
                    required: true
                    schema:
                        $ref: '#/definitions/ICategory'
    /api/professional_user:
        get:
            operationId: ProfessionalUserGet
            produces:
                - application/json
                - text/html
            responses:
                '200':
                    description: Success
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/IProfessionalUser'
                '500':
                    description: 'No connection to database'
                    schema:
                        type: string
            description: ""
            tags:
                - 'Professional Users'
            parameters: []
    '/api/professional_user/category/{category_id}':
        get:
            operationId: ProfessionalUserGetByCategory
            produces:
                - application/json
                - text/html
            responses:
                '200':
                    description: Success
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/IProfessionalUser'
                '400':
                    description: 'Bad request'
                    schema:
                        type: string
                '500':
                    description: 'No connection to database'
                    schema:
                        type: string
            description: ""
            tags:
                - 'Professional Users'
            parameters:
                -
                    description: ""
                    in: path
                    name: category_id
                    required: true
                    type: number
                    format: double
    '/api/professional_user/{id}':
        get:
            operationId: ProfessionalUserGetById
            produces:
                - application/json
                - text/html
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/IProfessionalUser'
                '404':
                    description: 'User not found'
                    schema:
                        type: string
                '500':
                    description: 'No connection to database'
                    schema:
                        type: string
            description: ""
            tags:
                - 'Professional Users'
            parameters:
                -
                    description: ""
                    in: path
                    name: id
                    required: true
                    type: number
                    format: double
swagger: '2.0'
securityDefinitions:
    default:
        type: apiKey
        name: x-auth
        in: header
