basePath: null
definitions:
    ICategory:
        description: ""
        properties:
            id:
                type: number
                format: double
                description: ""
            name:
                type: string
                description: ""
        type: object
        required:
            - id
            - name
    IUp:
        description: ""
        properties:
            id:
                type: number
                format: double
                description: ""
            email:
                type: string
                description: ""
            name:
                type: string
                description: ""
            lastname:
                type: string
                description: ""
            dni:
                type: string
                description: ""
            province:
                type: string
                description: ""
            city:
                type: string
                description: ""
            tel:
                type: string
                description: ""
            link:
                type: string
                description: ""
            about_me:
                type: string
                description: ""
            gender:
                enum:
                    - Masculino
                    - Femenino
                    - Otro
                type: string
                description: ""
            birthdate:
                type: string
                description: ""
            auth_number:
                type: string
                description: ""
            img:
                type: string
                description: ""
            created_at:
                type: string
                description: ""
            category_id:
                type: string
                description: ""
        type: object
        required:
            - email
            - name
            - lastname
            - dni
            - province
            - city
            - tel
            - gender
            - birthdate
            - category_id
info:
    description: 'FastWork API.'
    license:
        name: ISC
    title: fastwork-api
    version: 1.0.0
paths:
    /api/categories:
        get:
            operationId: CategoriesGet
            produces:
                - application/json
                - text/html
            responses:
                '200':
                    description: Succes
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/ICategory'
                '500':
                    description: 'No connection to database'
                    schema:
                        type: string
            description: ""
            parameters: []
    /api/up:
        get:
            operationId: UsersGet
            produces:
                - application/json
                - text/html
            responses:
                '200':
                    description: Succes
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/IUp'
                '500':
                    description: 'No connection to database'
                    schema:
                        type: string
            description: ""
            parameters: []
    '/api/up/category/{category_id}':
        get:
            operationId: UsersGetByCategory
            produces:
                - application/json
                - text/html
            responses:
                '200':
                    description: Succes
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/IUp'
                '404':
                    description: 'There are no users with those trades'
                    schema:
                        type: string
                '500':
                    description: 'No connection to database'
                    schema:
                        type: string
            description: ""
            parameters:
                -
                    description: ""
                    in: path
                    name: category_id
                    required: true
                    type: number
                    format: double
swagger: '2.0'
securityDefinitions:
    'client secret':
        type: apiKey
        name: x-auth
        in: header
